import BackgroundImage from '@/components/BackgroundImage'
import BlurModeButton from '@/components/BlurModeButton'
import Navbar from '@/components/Navbar'
import Screen from '@/components/Screen'
import SideBar from '@/components/SideBar'
import { selectBlurMode } from '@/reducers/blurSlice/blurSlice'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux'


export default function Home() {

  const BlurValue=useSelector(selectBlurMode);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>cteam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <header>
        <Navbar/>
      </header>
      <main className="">
        <div className={`transition-opacity delay-120 duration-300 ${BlurValue===4 ? `opacity-0` : `visible`}`}><SideBar/></div>
         <BackgroundImage/>
          <div className={`transition-opacity delay-120 duration-300 ${BlurValue===4 ? `opacity-0` : `visible`}`}><Screen/></div>
         <BlurModeButton/>
      </main>
    
    </>
  )
}
